Algoritmo "Estruturas de controle"
// Disciplina  : (Linguagem e Lógica de Programação)
// Professor   : Antonio Carlos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/05/2023
Var
// Seção de Declarações das variáveis 
   nota1, nota2, media: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo